// pico_cp_ui.cpp
//
// SH1106 + rotary-encoder UI for the Reface CP effect chain.
// Matches the project's existing u8g2 / encoder / push-button UI patterns.
// Generated by glm-5.2:cloud, formally reviewed; assembled by the orchestrator.

#include "pico_cp_ui.h"
#include "pico_userinterface.h"   // pico_UserInterfaceSelectionList
#include "pico/stdlib.h"
#include "ipc.h"                   // inter-core FIFO: route FX edits to Core 0
#include <cstdio>
#include <cstring>

// ---------------------------------------------------------------------------
// Edit a normalized 0..1 value (step 0.01), shown as an integer percent.
// ---------------------------------------------------------------------------
static float cpEditFloat(u8g2_t* u8g2, Encoder* enc, PushButton* bt,
                         const char* title, float cur)
{
    const float step = 0.01f;
    uint32_t last = to_ms_since_boot(get_absolute_time());

    while (true) {
        ui_poll_usb(); int32_t d = enc->delta();
        if (d > 0) {
            cur += step;
            last = to_ms_since_boot(get_absolute_time());
        } else if (d < 0) {
            cur -= step;
            last = to_ms_since_boot(get_absolute_time());
        }
        if (cur < 0.0f) cur = 0.0f;
        if (cur > 1.0f) cur = 1.0f;

        if (bt->ReadButton() == PushButton::PRESSED) { ui_wait_button_release(bt); return cur; }

        if (to_ms_since_boot(get_absolute_time()) - last > 8000) return cur;

        u8g2_FirstPage(u8g2);
        do {
            u8g2_SetFont(u8g2, u8g2_font_8x13B_tf);
            u8g2_DrawStr(u8g2, 0, 13, title);
            char buf[16];
            int pct = (int)(cur * 100.0f + 0.5f);
            snprintf(buf, sizeof(buf), "%d%%", pct);
            int w = u8g2_GetStrWidth(u8g2, buf);
            u8g2_DrawStr(u8g2, (128 - w) / 2, 48, buf);
        } while (u8g2_NextPage(u8g2));
    }
}

// ---------------------------------------------------------------------------
// Edit an int 0..2 (a 3-position switch), shown by name.
// ---------------------------------------------------------------------------
static int cpEditMode(u8g2_t* u8g2, Encoder* enc, PushButton* bt,
                      const char* title, int cur,
                      const char* n0, const char* n1, const char* n2)
{
    const char* names[3] = { n0, n1, n2 };
    uint32_t last = to_ms_since_boot(get_absolute_time());

    while (true) {
        ui_poll_usb(); int32_t d = enc->delta();
        if (d > 0) {
            cur = (cur + 1) % 3;
            last = to_ms_since_boot(get_absolute_time());
        } else if (d < 0) {
            cur = (cur + 2) % 3;
            last = to_ms_since_boot(get_absolute_time());
        }

        if (bt->ReadButton() == PushButton::PRESSED) { ui_wait_button_release(bt); return cur; }

        if (to_ms_since_boot(get_absolute_time()) - last > 8000) return cur;

        u8g2_FirstPage(u8g2);
        do {
            u8g2_SetFont(u8g2, u8g2_font_8x13B_tf);
            u8g2_DrawStr(u8g2, 0, 13, title);
            const char* name = names[cur];
            int w = u8g2_GetStrWidth(u8g2, name);
            u8g2_DrawStr(u8g2, (128 - w) / 2, 48, name);
        } while (u8g2_NextPage(u8g2));
    }
}

// ---------------------------------------------------------------------------
// Top-level CP effects editor: scrollable parameter list -> per-param editor.
// ---------------------------------------------------------------------------
int pico_UserInterfaceCpEffects(u8g2_t* u8g2, Encoder* enc, PushButton* bt, RefaceCpChain* fx)
{
    static const char* list =
        "Drive\n"
        "T/W Mode\n"
        "T/W Depth\n"
        "T/W Rate\n"
        "C/P Mode\n"
        "C/P Depth\n"
        "C/P Speed\n"
        "Delay Mode\n"
        "Delay Depth\n"
        "Delay Time\n"
        "Reverb\n"
        "Volume\n"
        "<< BACK";

    uint8_t startpos = 0;

    for (;;)
    {
        uint8_t sel = pico_UserInterfaceSelectionList(u8g2, enc, bt, "CP EFFECTS", startpos, list);
        startpos = sel;

        if (sel >= 12)
            return -1;

        switch (sel)
        {
            case 0: {
                float val = cpEditFloat(u8g2, enc, bt, "Drive", fx->getDrive());
                ipc_send_fx_param(FX_DRIVE, val);
                break;
            }
            case 1: {
                int val = cpEditMode(u8g2, enc, bt, "T/W Mode", fx->getTremWahMode(), "Off", "Tremolo", "Wah");
                ipc_send_fx_mode(FXM_TW_MODE, (uint8_t)val);
                break;
            }
            case 2: {
                float val = cpEditFloat(u8g2, enc, bt, "T/W Depth", fx->getTremWahDepth());
                ipc_send_fx_param(FX_TW_DEPTH, val);
                break;
            }
            case 3: {
                float val = cpEditFloat(u8g2, enc, bt, "T/W Rate", fx->getTremWahRate());
                ipc_send_fx_param(FX_TW_RATE, val);
                break;
            }
            case 4: {
                int val = cpEditMode(u8g2, enc, bt, "C/P Mode", fx->getChoPhaMode(), "Off", "Chorus", "Phaser");
                ipc_send_fx_mode(FXM_CP_MODE, (uint8_t)val);
                break;
            }
            case 5: {
                float val = cpEditFloat(u8g2, enc, bt, "C/P Depth", fx->getChoPhaDepth());
                ipc_send_fx_param(FX_CP_DEPTH, val);
                break;
            }
            case 6: {
                float val = cpEditFloat(u8g2, enc, bt, "C/P Speed", fx->getChoPhaSpeed());
                ipc_send_fx_param(FX_CP_SPEED, val);
                break;
            }
            case 7: {
                int val = cpEditMode(u8g2, enc, bt, "Delay Mode", fx->getDelayMode(), "Off", "Digital", "Analog");
                ipc_send_fx_mode(FXM_DLY_MODE, (uint8_t)val);
                break;
            }
            case 8: {
                float val = cpEditFloat(u8g2, enc, bt, "Delay Depth", fx->getDelayDepth());
                ipc_send_fx_param(FX_DLY_DEPTH, val);
                break;
            }
            case 9: {
                float val = cpEditFloat(u8g2, enc, bt, "Delay Time", fx->getDelayTime());
                ipc_send_fx_param(FX_DLY_TIME, val);
                break;
            }
            case 10: {
                float val = cpEditFloat(u8g2, enc, bt, "Reverb", fx->getReverbDepth());
                ipc_send_fx_param(FX_REVERB, val);
                break;
            }
            case 11: {
                float val = cpEditFloat(u8g2, enc, bt, "Volume", fx->getVolume());
                ipc_send_fx_param(FX_VOLUME, val);
                break;
            }
            default:
                break;
        }
    }
}
