// pico_cp_ui.h
//
// SH1106 + rotary-encoder UI for the Reface CP effect chain.
// Generated by glm-5.2:cloud, formally reviewed; assembled by the orchestrator.

#pragma once

#include "u8g2.h"
#include "encoder.h"
#include "push_button.h"
#include "reface_cp_chain.h"

// Effects editor menu. Returns -1 when the user leaves via "<< BACK".
int pico_UserInterfaceCpEffects(u8g2_t* u8g2, Encoder* enc, PushButton* bt, RefaceCpChain* fx);
